# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import script_builder.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csv-files')),
            ],
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_name', models.CharField(max_length=200)),
                ('new_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'permissions': (('view_datafield', 'View Data Field'),),
            },
            bases=(models.Model, script_builder.models.PermissionedModel),
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
                ('type_function', models.CharField(max_length=200)),
            ],
            options={
                'permissions': (('view_fieldtype', 'View Pivot Field'),),
            },
            bases=(models.Model, script_builder.models.PermissionedModel),
        ),
        migrations.CreateModel(
            name='MungerBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('munger_name', models.CharField(max_length=200)),
                ('munger_template', models.FilePathField(default='pandas_munger_template_basic.html', max_length=200, path='script_builder/templates/munger_templates')),
                ('input_path', models.CharField(blank=True, default='', max_length=999)),
                ('output_path', models.CharField(blank=True, default='', max_length=999)),
                ('rows_to_delete_top', models.IntegerField(default=0)),
                ('rows_to_delete_bottom', models.IntegerField(default=0)),
                ('is_sample', models.BooleanField(default=False)),
                ('default_aggregate_field_type', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='script_builder.FieldType')),
                ('field_types', models.ManyToManyField(related_name='munger_builder', related_query_name='munger_builder', to='script_builder.FieldType')),
            ],
            options={
                'permissions': (('view_mungerbuilder', 'View Munger'),),
            },
            bases=(models.Model, script_builder.models.PermissionedModel),
        ),
        migrations.CreateModel(
            name='PivotField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('data_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pivot_fields', related_query_name='pivot_fields', to='script_builder.DataField')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pivot_fields', related_query_name='pivot_fields', to='script_builder.FieldType')),
            ],
            options={
                'permissions': (('view_pivotfield', 'View Pivot Field'),),
            },
            bases=(models.Model, script_builder.models.PermissionedModel),
        ),
        migrations.AddField(
            model_name='datafield',
            name='munger_builder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_fields', related_query_name='data_fields', to='script_builder.MungerBuilder'),
        ),
    ]
