# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mungerbuilder',
            name='rows_to_delete_bottom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mungerbuilder',
            name='rows_to_delete_top',
            field=models.IntegerField(default=0),
        ),
    ]
