# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_builder', '0002_auto_20160801_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='mungerbuilder',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
